apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: hello-world
  description: Hello World example for gRPC
spec:
  type: grpc
  lifecycle: deprecated
  owner: team-c
  definition:
    $text: https://petstore.swagger.io/v2/swagger.json